import matplotlib.pyplot as plt
import numpy as np

a = np.load("Pic4.npy")
a = a.reshape((-1,28,28))

w=28
h=28
fig=plt.figure()
columns = 8
rows = 8
for i in range(1, 65):
	img = a[i-1]
	fig.add_subplot(rows, columns, i)
	plt.imshow(img)
	plt.axis('off')
plt.show()

[776.7548304937342,276.61566305670146,253.34933629798005,241.2473427485814,232.39870368549182,224.7888991523331,218.68175427412987,213.65287826672835]

[774.8855007946624,279.64268177046773,255.2203680427279,241.7920625176794,231.80424617716307,224.531575934032,217.4163809076723,212.34533307951418]


-> 0 : 0  k: 5  h: 64  Error: 776.4715874586162
-> 0 : 10000  k: 5  h: 64  Error: 277.41071095230245
-> 0 : 20000  k: 5  h: 64  Error: 253.85105354463877
-> 0 : 30000  k: 5  h: 64  Error: 240.48910101310443
-> 0 : 40000  k: 5  h: 64  Error: 230.97199380008112
-> 0 : 50000  k: 5  h: 64  Error: 222.65388432306935
-> 1 : 0  k: 5  h: 64  Error: 216.95301487726812
-> 1 : 10000  k: 5  h: 64  Error: 211.4165935173089


-> 0 : 0  k: 10  h: 64  Error: 772.3909475898195
-> 0 : 10000  k: 10  h: 64  Error: 278.39167789470906
-> 0 : 20000  k: 10  h: 64  Error: 252.51764288433566
-> 0 : 30000  k: 10  h: 64  Error: 239.00048063639258
-> 0 : 40000  k: 10  h: 64  Error: 230.3988253447
-> 0 : 50000  k: 10  h: 64  Error: 224.40969729817604
-> 1 : 0  k: 10  h: 64  Error: 216.37495100393213
-> 1 : 10000  k: 10  h: 64  Error: 211.45524847805927

